### ISSUE TITLE
installation error

### ISSUE THREAD

**Issue by DRYGOIYGOL** [Stephanzion/YandexMusicBetaMod#19]
[ 23:00:38 ] Запуск...
[ 23:00:40 ] Ошибка запуска патчера:

System.IO.IOException: Access to the path '\\?\C:\Program Files\YandexMusicPatcher\temp' is denied.
   at System.IO.FileSystem.RemoveDirectoryInternal(String fullPath, Boolean topLevel, Boolean allowDirectoryNotEmpty)
   at System.IO.FileSystem.RemoveDirectoryRecursive(String fullPath, WIN32_FIND_DATA& findData, Boolean topLevel)
   at System.IO.FileSystem.RemoveDirectory(String fullPath, Boolean recursive)
   at YandexMusicPatcherGui.Main.<button1_Click>b__6_0() in V:\Repos\YandexMusicBetaMod\Main.cs:line 167
[ 23:00:58 ] Ошибка запуска патчера:

System.IO.IOException: Access to the path '\\?\C:\Program Files\YandexMusicPatcher\temp' is denied.
   at System.IO.FileSystem.RemoveDirectoryInternal(String fullPath, Boolean topLevel, Boolean allowDirectoryNotEmpty)
   at System.IO.FileSystem.RemoveDirectoryRecursive(String fullPath, WIN32_FIND_DATA& findData, Boolean topLevel)
   at System.IO.FileSystem.RemoveDirectory(String fullPath, Boolean recursive)
   at YandexMusicPatcherGui.Main.<button1_Click>b__6_0() in V:\Repos\YandexMusicBetaMod\Main.cs:line 167
[ 23:01:05 ] Ошибка запуска патчера:

System.IO.IOException: Access to the path '\\?\C:\Program Files\YandexMusicPatcher\temp' is denied.
   at System.IO.FileSystem.RemoveDirectoryInternal(String fullPath, Boolean topLevel, Boolean allowDirectoryNotEmpty)
   at System.IO.FileSystem.RemoveDirectoryRecursive(String fullPath, WIN32_FIND_DATA& findData, Boolean topLevel)
   at System.IO.FileSystem.RemoveDirectory(String fullPath, Boolean recursive)
   at YandexMusicPatcherGui.Main.<button1_Click>b__6_0() in V:\Repos\YandexMusicBetaMod\Main.cs:line 167

< the antivirus is turned off, the admin rights are granted, the installation folder is empty.>

**Comment by Stephanzion** [comment]
Please specify which version and build of windows you are using

**Comment by Stephanzion** [comment]
I'm closing the issue as there has been no response
