### ISSUE TITLE
Error Start

### ISSUE THREAD

**Issue by EndermanHack19** [Stephanzion/YandexMusicBetaMod#20]
```
System.UnauthorizedAccessException: Access to the path 'chrome_100_percent.pak' is denied.
   at System.IO.FileSystem.RemoveDirectoryRecursive(String fullPath, WIN32_FIND_DATA& findData, Boolean topLevel)
   at System.IO.FileSystem.RemoveDirectory(String fullPath, Boolean recursive)
   at YandexMusicPatcherGui.Main.<button1_Click>b__6_0() in V:\Repos\YandexMusicBetaMod\Main.cs:line 170
```
![2024-10-15 182056](https://github.com/user-attachments/assets/e792c54a-0c49-4136-bcd5-aad3f57bb1d2)

**Comment by Stephanzion** [comment]
Скорее всего запустили не от имени администратора
