### ISSUE TITLE
не заходит в приложение

### ISSUE THREAD

**Issue by Orlovvv01** [Stephanzion/YandexMusicBetaMod#24]
У меня просто не заходит в приложение
![{98CD430B-6400-4A7B-BAF8-9B3041D2CFCC}](https://github.com/user-attachments/assets/eba1cc20-2843-4be7-8866-8a815bff299c)

**Comment by Stephanzion** [comment]
скиньте логи патчера, после того как он все установил

**Comment by Orlovvv01** [comment]
пишет патчер это:
[ 22:26:14 ] Ошибка запуска патчера:

System.Net.WebException: Подключение не установлено, т.к. конечный компьютер отверг запрос на подключение. [::ffff:127.0.0.1]:8085 (127.0.0.1:8085)
 ---> System.Net.Http.HttpRequestException: Подключение не установлено, т.к. конечный компьютер отверг запрос на подключение. [::ffff:127.0.0.1]:8085 (127.0.0.1:8085)
 ---> System.Net.Sockets.SocketException (10061): Подключение не установлено, т.к. конечный компьютер отверг запрос на подключение. [::ffff:127.0.0.1]:8085
   at System.Net.Sockets.Socket.DoConnect(EndPoint endPointSnapshot, SocketAddress socketAddress)
   at System.Net.Sockets.Socket.Connect(EndPoint remoteEP)
   at System.Net.Sockets.Socket.Connect(String host, Int32 port)
   at System.Net.Sockets.Socket.Connect(EndPoint remoteEP)
   at System.Net.HttpWebRequest.<>c__DisplayClass219_0.<<CreateHttpClient>b__1>d.MoveNext()
--- End of stack trace from previous location ---
   at System.Net.Http.HttpConnectionPool.ConnectToTcpHostAsync(String host, Int32 port, HttpRequestMessage initialRequest, Boolean async, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at System.Net.Http.HttpConnectionPool.ConnectToTcpHostAsync(String host, Int32 port, HttpRequestMessage initialRequest, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.ConnectAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.CreateHttp11ConnectionAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.AddHttp11ConnectionAsync(QueueItem queueItem)
   at System.Threading.Tasks.TaskCompletionSourceWithCancellation`1.WaitWithCancellationAsync(CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.SendWithVersionDetectionAndRetryAsync(HttpRequestMessage request, Boolean async, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.EstablishProxyTunnelAsync(Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.ConnectAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.CreateHttp11ConnectionAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.AddHttp11ConnectionAsync(QueueItem queueItem)
   at System.Threading.Tasks.TaskCompletionSourceWithCancellation`1.WaitWithCancellation(CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.SendWithVersionDetectionAndRetryAsync(HttpRequestMessage request, Boolean async, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.HttpMessageHandlerStage.Send(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.DiagnosticsHandler.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpMessageHandlerStage.Send(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.Metrics.MetricsHandler.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpMessageHandlerStage.Send(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.SocketsHttpHandler.Send(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.Send(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationToken cancellationToken)
   at System.Net.HttpWebRequest.SendRequest(Boolean async)
   at System.Net.HttpWebRequest.GetResponse()
   --- End of inner exception stack trace ---
   at System.Net.HttpWebRequest.GetResponse()
   at System.Net.WebClient.GetWebResponse(WebRequest request)
   at System.Net.WebClient.DownloadBits(WebRequest request, Stream writeStream)
   at System.Net.WebClient.DownloadDataInternal(Uri address, WebRequest& request)
   at System.Net.WebClient.DownloadString(Uri address)
   at YandexMusicPatcherGui.Patcher.DownloadLastestMusic() in V:\Repos\YandexMusicBetaMod\Patcher.cs:line 124
   at YandexMusicPatcherGui.Main.<button1_Click>b__6_0() in V:\Repos\YandexMusicBetaMod\Main.cs:line 172

**Comment by Stephanzion** [comment]
Давайте проверим, доступны ли вам сервера Яндекса. Попробуйте открыть в браузере [эту ссылку](https://music-desktop-application.s3.yandex.net/stable/Yandex_Music_x64_5.24.1.exe), она используется для скачивания приложения. Судя по логам - патчеру не смог ее открыть.

Если все работает - начнет скачиваться установщик оригинальной Яндекс Музыки.

**Comment by Orlovvv01** [comment]
оригинальная яндекс музыка скачалась

**Comment by Stephanzion** [comment]
У вас запущены прокси или впн?

**Comment by Orlovvv01** [comment]
нет

**Comment by Stephanzion** [comment]
Получил похожую ошибку когда выключил патчеру доступ в интернет через фаервол. Либо вы тоже как то ограничили патчеру выход в сеть либо это сделал ваш антивирус

**Comment by Orlovvv01** [comment]
ничего не помогает

**Comment by Stephanzion** [comment]
Больше у меня вариантов по решению нет. Вы можете [скачать готовый билд Яндекс Музыки](https://github.com/Stephanzion/YandexMusicBetaMod/raw/refs/heads/master/Portable/YandexMusic.7z) со стандартными модами, возможно вам подойдет такой вариант.

**Comment by Orlovvv01** [comment]
это тоже не помогло

**Comment by Stephanzion** [comment]
а обычную яндекс музыку ставили? Там все работает?

**Comment by Orlovvv01** [comment]
У меня нет подписки Плюс

**Comment by Stephanzion** [comment]
Сделал вам [отдельную версию приложения](https://drive.google.com/file/d/1GBQo5Pn7fiVyGjqPGdm1P76wJWcxJHts/view?usp=sharing) со включенной консолью. Разархивируйте все файлы в папку и запустите приложение. После запуска откройте консоль сочетанием клавиш ctrl shift i. Вврху консоли выберите вкладку network. Затем не закрывая консоль перейдите в приложение и нажмите на кнопку "перезагрузить приложение". После обновления страницы скиньте скришот вкладки network и console из консоли, которую открыли ранее.

**Comment by Orlovvv01** [comment]
![Uploading {F3108919-D1FC-4F27-9682-92F52430A398}.png…]()

**Comment by Orlovvv01** [comment]
![{F3108919-D1FC-4F27-9682-92F52430A398}](https://github.com/user-attachments/assets/fb35973d-6eea-49b1-b422-9ed8e56bd7ac)

**Comment by Stephanzion** [comment]
Нажмите на fetch/xhr и скиньте еще раз скрин пожалуйста. Если после этого появятся красные строчки можно на них нажать чтобы открыть на весь экран.

![image](https://github.com/user-attachments/assets/3002f584-f8e0-4df0-b775-8e3bf72a3652)

**Comment by Orlovvv01** [comment]
![Uploading {9D962BF2-DB4E-4580-880A-F873D4E169B9}.png…]()

**Comment by Orlovvv01** [comment]
![Uploading {9D962BF2-DB4E-4580-880A-F873D4E169B9}.png…]()

**Comment by Stephanzion** [comment]
подождите пока загрузится перед тем как нажимать кнопку comment)

**Comment by Orlovvv01** [comment]
![{9D962BF2-DB4E-4580-880A-F873D4E169B9}](https://github.com/user-attachments/assets/d8045d5c-021a-44f8-ad8a-b567f8b565b0)

**Comment by Stephanzion** [comment]
хорошо, и теперь скриншот вкладки console. Если в экран все не поместится, то промотайте в самый верх. Меня интересуют ошибки выделенные красным цветом

**Comment by Orlovvv01** [comment]
![{DBD190C1-0179-4C4B-8443-6B05D07FE3B5}](https://github.com/user-attachments/assets/693822db-bb9d-4eec-ae9c-9d4ba8808cf5)

**Comment by Stephanzion** [comment]
промотайте ниже, нужны сточки которые имеют красную подложку

**Comment by Stephanzion** [comment]
Еще можете попробовать закрыть приложение, удалить папку %appdata%\YandexMusic (можно вставить этот путь в проводник) и затем снова запустить приложение, это почистит кэш.

**Comment by Orlovvv01** [comment]
![{6A3A9098-E87B-4773-A579-AC391C52FA52}](https://github.com/user-attachments/assets/636d4096-9e3a-48a8-ac92-9005b6cc8727)

**Comment by Stephanzion** [comment]
У вас открывалась страница входа перед тем как вы сталкивались с ошибками? Лоигинились в аккаунт?

**Comment by Orlovvv01** [comment]
да, открывалась, а до ошибки я логинисля в аккаунт

**Comment by Stephanzion** [comment]
это уже что то. Ранее ко мне обращался человек у которого по какой то причине не удавалось зайти с определенного аккаунта, но нам так и не удалось выяснить причину. Единственное, что мы установили это то, что на другом аккаунте у него все заработало. У вас есть еще один какой нибудь аккаунт?

**Comment by Orlovvv01** [comment]
проблема в том, то что даже залогиниться из-за ошибки нельзя, а я имел ввиду, что я логинился раньше, ещё где-то в сентябре

**Comment by Stephanzion** [comment]
Также откройте в браузере [эту ссылку](https://api.music.yandex.net/account/experiments/details). В консоли указнано, что ее не удалось открыть. Скидывать скрин не нужно, просто убедитесь что нет никакой ошибки

**Comment by Orlovvv01** [comment]
там текст какой-то
![{AE00029A-48C2-4DEE-9B43-665D370B44E6}](https://github.com/user-attachments/assets/c83d9ff8-05ad-43c5-b1e5-d901c6c997f1)

**Comment by Orlovvv01** [comment]
так и должно быть?

**Comment by Stephanzion** [comment]
да, все нормально

**Comment by Orlovvv01** [comment]
ну, страница открылась

**Comment by Stephanzion** [comment]
> проблема в том, то что даже залогиниться из-за ошибки нельзя, а я имел ввиду, что я логинился раньше, ещё где-то в сентябре

[Выше писал ](https://github.com/Stephanzion/YandexMusicBetaMod/issues/24#issuecomment-2424094273)как принудительно разлогиниться с вашего старого аккаунта. Если есть возможность нужно попробовать зайти на левый аккаунт

**Comment by Orlovvv01** [comment]
возможности нет
к сожалению

**Comment by Stephanzion** [comment]
Убедитесь что здесь у вас не стоит никаких настроек
![image](https://github.com/user-attachments/assets/27d5919e-004c-4c18-b674-b60b19130b13)
![image](https://github.com/user-attachments/assets/d422a5db-6b50-44a7-a2de-3e21cacbe50f)

**Comment by Orlovvv01** [comment]
отключил

**Comment by Stephanzion** [comment]
> отключил

То есть раньше было включено? Изменения есть?

**Comment by Orlovvv01** [comment]
Да, теперь всё работает
